# Generated by Django 6.0.4 on 2026-05-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('web', 'Application Web'), ('api', 'API Backend'), ('desktop', 'Application Desktop'), ('mobile', 'Application Mobile'), ('erp', 'ERP / Gestion'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('in_progress', 'En cours'), ('maintenance', 'Maintenance')], default='completed', max_length=20, verbose_name='Statut')),
                ('description_short', models.CharField(max_length=300, verbose_name='Description courte')),
                ('description_full', models.TextField(verbose_name='Description complète')),
                ('architecture', models.CharField(blank=True, max_length=200, verbose_name='Architecture')),
                ('database_info', models.CharField(blank=True, max_length=100, verbose_name='Base de données')),
                ('features', models.TextField(blank=True, verbose_name='Fonctionnalités backend (une par ligne)')),
                ('thumbnail', models.ImageField(blank=True, upload_to='projects/thumbnails/', verbose_name='Miniature')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Démo')),
                ('icon', models.CharField(default='🔧', max_length=10, verbose_name='Icône (emoji)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#3b82f6', max_length=10)),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Image du projet',
                'verbose_name_plural': 'Images du projet',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='projects.technology'),
        ),
    ]
