# Generated by Django 6.0.4 on 2026-05-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('issuer', models.CharField(max_length=100, verbose_name='Organisme')),
                ('date', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('url', models.URLField(blank=True, verbose_name='Lien certificat')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='Diplôme')),
                ('institution', models.CharField(max_length=200, verbose_name='Établissement')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('start_year', models.PositiveIntegerField(verbose_name='Année début')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Poste / Titre')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation')),
                ('start_date', models.DateField(verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=200, verbose_name='Titre professionnel')),
                ('tagline', models.CharField(max_length=300, verbose_name='Accroche')),
                ('bio_short', models.TextField(verbose_name='Bio courte')),
                ('bio_long', models.TextField(verbose_name='Bio complète')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='Photo')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, upload_to='cv/', verbose_name='CV (PDF)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('years_experience', models.PositiveIntegerField(default=2)),
                ('projects_count', models.PositiveIntegerField(default=10)),
                ('technologies_count', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technologie')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('database', 'Base de données'), ('frontend', 'Frontend'), ('devops', 'DevOps / Outils'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('percentage', models.PositiveIntegerField(default=70, verbose_name='Niveau (%)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (emoji/class)')),
                ('color', models.CharField(default='#3b82f6', max_length=255, verbose_name='Couleur hex')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'name'],
            },
        ),
    ]
