# Generated by Django 6.0.4
import os
from django.db import migrations, models
from django.contrib.auth.hashers import make_password
from cloudinary_storage.storage import RawMediaCloudinaryStorage

def create_initial_data(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    Education = apps.get_model('core', 'Education')
    Skill = apps.get_model('core', 'Skill')
    User = apps.get_model('auth', 'User')

    # Création du superutilisateur si défini dans l'environnement
    superuser_name = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    if superuser_name:
        if not User.objects.filter(username=superuser_name).exists():
            User.objects.create(
                username=superuser_name,
                email=os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com'),
                password=make_password(os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'password')),
                is_superuser=True,
                is_staff=True,
                is_active=True
            )

    # 1. Paramètres globaux
    SiteSettings.objects.update_or_create(
        id=1,
        defaults={
            'name': 'AGBOKA FARID',
            'title': 'Développeur Backend',
            'tagline': "Développeur backend passionné par Python et Django, spécialisé en conception d'APIs robustes, architecture logicielle et bases de données relationnelles.",
            'bio_short': "développeur backend de 20 ans basé à Lomé, Togo.",
            'bio_long': "Je m'appelle AGBOKA FARID, développeur backend de 20 ans basé à Lomé, Togo. Python est mon langage de prédilection.",
            'email': 'agbokafarid@gmail.com',
            'phone': '+228 91 13 51 72',
            'location': 'Zossimé, Lomé — Togo',
            'whatsapp': '22891135172',
            'github': 'https://github.com/faridxdev',
            'linkedin': 'https://linkedin.com/in/agbokafarid',
            'is_available': True,
            'projects_count': 6,
            'technologies_count': 14,
            'years_experience': 2,
        }
    )

    # 2. Formations
    Education.objects.update_or_create(
        degree="Licence en informatique : Développement d'Applications",
        institution="Institut FORMATEC",
        defaults={
            'location': 'Lomé, Togo',
            'start_year': 2023,
            'is_current': True,
            'description': "Spécialisation backend, bases de données.",
            'order': 1
        }
    )

    # 3. Compétences (Skills)
    skills_data = [
        ('Python', 'backend', 88, 1, 'linear-gradient(90deg,var(--python),var(--python2))'),
        ('Django', 'backend', 85, 2, 'linear-gradient(90deg,var(--python),var(--python2))'),
        ('Django REST Framework', 'backend', 80, 3, 'linear-gradient(90deg,var(--python),var(--python2))'),
        ('OpenCV / DeepFace', 'backend', 72, 4, 'linear-gradient(90deg,var(--python),var(--python2))'),
        ('Laravel', 'backend', 80, 5, '#f59e0b'),
        ('PHP', 'backend', 75, 6, '#f59e0b'),
        ('Java / Java Swing', 'backend', 70, 7, '#ef4444'),
        ('PostgreSQL', 'database', 82, 8, '#3b82f6'),
        ('MySQL', 'database', 82, 9, '#3b82f6'),
        ('SQLite', 'database', 75, 10, '#3b82f6'),
        ('JMerise / Modélisation', 'database', 78, 11, '#3b82f6'),
        ('HTML / CSS / Bootstrap', 'frontend', 78, 12, '#8b5cf6'),
        ('Tailwind CSS', 'frontend', 74, 13, '#8b5cf6'),
        ('JavaScript', 'frontend', 65, 14, '#8b5cf6'),
        ('Git / GitHub', 'devops', 78, 15, '#6366f1'),
    ]

    for name, cat, pct, order, color in skills_data:
        Skill.objects.update_or_create(
            name=name,
            defaults={
                'category': cat,
                'percentage': pct,
                'order': order,
                'color': color,
                'is_featured': True
            }
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('issuer', models.CharField(max_length=100, verbose_name='Organisme')),
                ('date', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('url', models.URLField(blank=True, verbose_name='Lien certificat')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='Diplôme')),
                ('institution', models.CharField(max_length=200, verbose_name='Établissement')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('start_year', models.PositiveIntegerField(verbose_name='Année début')),
                ('end_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Poste / Titre')),
                ('organization', models.CharField(max_length=200, verbose_name='Organisation')),
                ('start_date', models.DateField(verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='En cours')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=200, verbose_name='Titre professionnel')),
                ('tagline', models.CharField(max_length=300, verbose_name='Accroche')),
                ('bio_short', models.TextField(verbose_name='Bio courte')),
                ('bio_long', models.TextField(verbose_name='Bio complète')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='Photo')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('cv_file', models.FileField(blank=True, storage=RawMediaCloudinaryStorage(), upload_to='cv/', verbose_name='CV (PDF)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('years_experience', models.PositiveIntegerField(default=2)),
                ('projects_count', models.PositiveIntegerField(default=10)),
                ('technologies_count', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Technologie')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('database', 'Base de données'), ('frontend', 'Frontend'), ('devops', 'DevOps / Outils'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('percentage', models.PositiveIntegerField(default=70, verbose_name='Niveau (%)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône (emoji/class)')),
                ('color', models.CharField(default='#3b82f6', max_length=255, verbose_name='Couleur hex')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(create_initial_data),
    ]
