# Generated by Django 6.0.4 on 2026-05-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Format ICO ou PNG (32x32)', upload_to='settings/', verbose_name='Favicon'),
        ),
    ]
