# Generated by Django 6.0.4 on 2026-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(choices=[('freelance', 'Projet Freelance'), ('job', 'Stage / Emploi'), ('collab', 'Collaboration'), ('other', 'Autre')], max_length=20, verbose_name='Sujet')),
                ('budget', models.CharField(blank=True, choices=[('negotiable', 'À définir'), ('less_300k', 'Moins de 300 000 FCFA'), ('300k_1m', '300 000 FCFA — 1 000 000 FCFA'), ('more_1m', 'Plus de 1 000 000 FCFA')], max_length=50, verbose_name='Budget')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé')], default='new', max_length=10, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
