# Generated by Django 6.0.4 on 2026-05-04 06:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('color', models.CharField(default='#3b82f6', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(max_length=400, verbose_name='Extrait')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenu')),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/', verbose_name='Image')),
                ('icon', models.CharField(default='📝', max_length=10, verbose_name='Icône')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
